//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Viewed Appetizer.
        /// </summary>
        internal static string appetizer {
            get {
                return ResourceManager.GetString("appetizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day`s Luck.
        /// </summary>
        internal static string happyday {
            get {
                return ResourceManager.GetString("happyday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen.
        /// </summary>
        internal static string kitchen {
            get {
                return ResourceManager.GetString("kitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry Today you dont have luck.
        /// </summary>
        internal static string kusmetofday {
            get {
                return ResourceManager.GetString("kusmetofday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Recipes.
        /// </summary>
        internal static string latestrecept {
            get {
                return ResourceManager.GetString("latestrecept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Viewed Main dishes.
        /// </summary>
        internal static string Maindishes {
            get {
                return ResourceManager.GetString("Maindishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Viewed Desserts.
        /// </summary>
        internal static string MostViewedDesserts {
            get {
                return ResourceManager.GetString("MostViewedDesserts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Viewed Recipes.
        /// </summary>
        internal static string MostViewedRecipes {
            get {
                return ResourceManager.GetString("MostViewedRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Viewed Soups.
        /// </summary>
        internal static string MostViewedSoups {
            get {
                return ResourceManager.GetString("MostViewedSoups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready For.
        /// </summary>
        internal static string ready {
            get {
                return ResourceManager.GetString("ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipe of the day.
        /// </summary>
        internal static string receptday {
            get {
                return ResourceManager.GetString("receptday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don`t have recipe of day.
        /// </summary>
        internal static string receptofday {
            get {
                return ResourceManager.GetString("receptofday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
    }
}
