// <auto-generated />
namespace Recepts.MVC.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_Product_And_Recept_Table_And_Fix_ReceptForDay : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Product_And_Recept_Table_And_Fix_ReceptForDay));
        
        string IMigrationMetadata.Id
        {
            get { return "201710212309083_Add_Product_And_Recept_Table_And_Fix_ReceptForDay"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
